package com.hqyg.test1;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/** 
* @author 作者 zhangshiping: 
* @version 创建时间：2019年8月27日 下午6:14:05 
* 类说明 
*/
public class ArrayListTest {

	
	public static void main(String[] args) {
		String[] str = new String[] { "ESFBAWHE", "UKFBAWHE", "FRFBAWHE", "DEFBAWHE", "USFBAWHO", "USFBAWHS", "UKFBAWHD",
				"CAFBAWHS", "ITFBAWHK", "FRFBAWHK", "ESFBAWHK", "RUEKT", "YBMYXNC", "GZYYC", "WZDFWH", "JPFBYISA",
				"JPFBYINI", "FXQHBSWH", "CAFBAS", "CAFBAW", "ESFBR", "FRFBB", "ITFBW", "DEFBK", "UKFBW", "FRFBW", "RUWJ",
				"KMMP", "KMKSA", "DEMBB", "ITFBS", "FRFBT", "DEPX", "UKPX", "EBHKZZWH", "EBSZZZWH", "USFBAWHG", "USFBAWHB",
				"JPFBAWHE", "JPFBAWHD", "JPFBAWHC", "JPFBAWHB", "ITFBAWHB", "FRFBAWHB", "ESFBAWHB", "DEFBAWHB", "CNSZ",
				"EBQHBSWH", "EBQHZZWH", "QHZZWH", "QHBSWH", "YUBESZWH", "VIDAXI", "NEWAIM", "VGWH", "DZWH", "JPFBAWH",
				"DEFBAWH", "UKFBAWH", "MXWH", "PCWH", "GBRUW", "EUK", "UK", "NY", "SZ", "SZXL", "ZHJNB", "DLPF", "LINGCAI",
				"USFBW", "RUEBF", "JPFBALY", "USFBAWHR", "JPFBYMD", "USFBAWHK", "CAFBAWHK", "MXFBAWHK", "UKFBA",
				"USFBYISINA", "UKFBYISINA", "ESFBYISINA", "FRFBYISINA", "UKLT", "YBTB", "DEFBAWHM", "ESFBAWHM", "UKFBAWHG",
				"ESFBAWHG", "FRFBAWHG", "UKFBAWHJ", "DEFBAWHI", "ESFBAWHI", "UKFBAWHK", "DEFBAWHK", "ST", "UKFBAWHH",
				"ESFBAWHH", "FRFBAWHH", "ITFBAWHH", "JPFBAWHG", "JPFBAWHF", "ESFBAWHL", "UKFBAWHO", "ESSMTWH", "UKFBAWHR",
				"FZDZN", "UKFBAZ", "FRFBAZ", "MXTJWH", "UKTJWH", "DEFBAW", "ITFBASL", "ESTJWH", "HKTJWH", "CAPXTJ",
				"AUPXTJ", "FXRUWJ", "USFBAXM", "GBFBAHHT", "FRFBAHHT", "ITFBAHHT", "XNFHC", "MXFBAHLD", "FXLAWH2",
				"WULIAOWH", "GBFBAMHS", "DEFBAMHS", "ESFBAMHS", "ITFBAMHS", "FRFBAMHS", "USFBAXCST", "DEFNTG", "AUFNTG",
				"DGWLC", "USFNTG", "IDJDYJD", "SZXWFN", "GBFBAMQ", "FXJFKGC", "DEFBAXB", "SHOUHOUBEIPINWH", "DGXWFN",
				"ESWXDZ", "SDLDF", "USEYKD", "IDXNSP", "FXDHQD", "DZXNQD", "PEIJIANWH", "GBFBAEL", "DEFBAEL", "FRFBAEL",
				"ITFBAEL", "ESFBAEL", "CAFBAXM", "GBZTYKD", "GBYKDFX", "GBYKDDZ", "GBYKDFZ", "YKDKHTJ", "MYXNSP", "HKB2BC",
				"KA", "DSFHQB", "GBFNTJ", "GBFNTJ2", "DEFBABE", "FRFBABE", "PEIJIANWX", "DZYJDFC", "HZSMTFX2", "USFBWMX",
				"HZSMTFX4", "ITFBAELE", "FZPCWH", "CZ4PXFX", "GB4PXDSF", "P_TYDFX", "FRFBARD", "DBARAMEXTJ", "GB4PXLU2",
				"GB4PXLU3", "GBYKDDSF2", "GBYKDFX2", "GBYKDDZ2", "DEDFCK", "PTDFCK", "USDFCK", "MYDFCK", "GBBMHTJ2",
				"CZ4PXCZPT1", "CZ4PXCZPT2", "BANYIWH", "SACYTJ", "AUDFCK", "PLDFCK", "BEDFCK", "YBSATJ", "DZCZBLG",
				"DZCZBLG1", "DEWHDSF", "XDNEWEGG", "CNSMTDFC", "ELSSMTDFC", "SZLIUJIUC", "AUSY", "USLAA", "GBFBAFOR",
				"FBFBAFOR", "DEFBAFOR", "ITFBAFOR", "ESFBAFOR", "USFBART", "ZYCXGSB", "USFBAM", "HTDK", "ITALYJC",
				"SPAINJC", "DERMJC", "NGFBJ02", "AEFBSSVT", "AEFBSMLY", "XIAWANXL", "RUIMULE", "DEHAIER", "ITHAIER",
				"ESHAIER", "ESTJWH2", "AEFBSYOKE", "USFBADY", "SUMAITAE", "USFBAZHE", "DSFTS", "ESTJWHFZ", "ESTJWHDSF",
				"ESTJWHFX", "CNFBWHANZ", "MXFBAMHS", "PHSHOPEE", "THSHOPEE", "CNGYSTO", "WULIULS", "AUFBAQJJ", "DEHEYTJ",
				"GBFLYING", "USFBAOA", "GBFBAOA", "DEFBAOA", "FRFBAOA", "ITFBAOA", "ESFBAOA", "DS", "ITGYSDF", "EKJUMIASS",
				"USGYSTO", "CLEARASIL", "DETUICANGG", "DEHEYUEC", "INFBAYOKE", "JPFBANOJ", "HTXNC", "UKFBAAZON",
				"ITFBAAZON", "ESFBAAZON", "DEFBAAZON", "FRFBAAZON", "UKAMAZON", "FRAMAZON", "DEAMAZON", "ESAMAZON",
				"USFBAAVI", "DEBONTALE", "USFBACDY", "CAFBACDY", "GBFBACDY", "DEFBACDY", "FRFBACDY", "ITFBACDY", "ESFBACDY",
				"JPFBACDY", "CAFBAJSS", "HKTJCK", "HDYGMX", "RUYJDA", "USLATJC", "CNHYCSD", "ESHYTJC", "PLHYTJC",
				"ESFBAZAAA", "USFBAYD", "JPFBALA", "DEHZC", "AEFBSAA", "AEFBSAB", "CHHZAA", "USZYCC", "USZYCE", "DZTS",
				"AENOON", "INHZCCC", "FRFBADE", "CNHYCSDD", "GBDSFLD", "AEHZCCC", "AEFTBCCCC", "HKHZCCWC", "GBFBAZJ",
				"VIDAXLL", "ZYCXGSBB", "AEFBNNO", "USFBWJU", "USFBWYY", "LYSOL", "CNHYCSDDD", "JPFBAFX", "JPFBADSF",
				"NGJUMIAZA", "EUFBWEU", "JPCHCGC", "TMCS", "B2BXNWH", "FXDJWH", "FXXN", "DSFXN", "DZXN", "CAFBATZE",
				"GBFBATZE", "DEFBATZE", "FRFBATZE", "ESFBATZE", "JPFBATZE", "EUFBWENS", "GBFBA06", "DEFBA07", "FRFBA07",
				"ITFBA07", "ESFBA07", "SZKP", "SDWH04", "INFBA02", "USFBW01", "USFBW02", "USFBW03", "USFBW04", "USFBW05",
				"USFBW06", "USFBW07", "USFBW08", "USFBW09", "USFBW10", "USFBW11", "USFBW12", "USFBW13", "USFBW14",
				"USFBW15", "USFBW16", "USFBW17", "KPDF", "USFBW18", "USFBW19", "USFBW20", "USFBW21", "USFBW22", "USFBW23",
				"USFBW24", "USFBW25", "USFBW26", "USFBW27", "USFBW28", "HKZYC15", "NGJUMIA01", "ICJUMIA01", "PHZYC01",
				"CPGYSDFC01", "DSFSNT01", "DSFFBW01", "DSFMAJUMIA02", "DZGX", "AEFXNOON01", "AEFXNOON02", "AEFXNOON03",
				"AEFXNOON04", "DEFXYJDF01", "DDSDSFJPFBA", "FHHC", "FXDEGYSDFCDC", "FXUSGYSDFCDC", "FXPLGYSDFCDC",
				"USFXYJDF01", "USFXYJDF02", "USDSFYJDF01", "CAFBAKYYJ190511", "CAFBAJSS190511", "DEFBAWM190511",
				"ESFBAWM190511", "DEFBASZ190511", "ESFBASZ190511", "GBFBA20190516", "DEFBA20190516", "FRFBA20190516",
				"ITFBA20190516", "ESFBA20190516", "JPFBA20190516", "DSFNX", "ESFBA20190522", "INFBA20190525",
				"FRMM20190528", "FRMM20190530", "CAFBA20190624", "NGJUMIA20190627", "GBFBA20190627", "FRFFBA20190627",
				"DEFBA20190627", "ITFBA20190627", "MMNC", "ICJUMIA20190703", "JHZZ", "GBFBA20190706", "DEFBA20190706",
				"FRFBA20190704", "ITFBA20190706", "ESFBA20190706", "USFBA20190706", "CAFBA20190706", "USFBA20190710",
				"HK20190711", "GBVIDA20190717", "DEVIDA20190717", "FRVIDA20190717", "ITVIDA20190717", "ESVIDA20190717",
				"BEVIDA20190717", "ITFBA20190722", "GBFBA20190722", "DEFBA20190722", "FRFBA20190722", "ESFBA20190722",
				"AEFBN20190722", "SZWZTS", "GBBR", "GBRU", "WZUSPX", "DEPXTJ", "USLAWH", "KEMNGC", "DEEDXN", "USLAW",
				"SZTSWH", "FXLAXGC", "UKCBWH", "CZ4PXDZ", "FREDCGC", "XNBLC", "FXLAWH", "GBSPAW", "GBNY", "FRFBCCD",
				"USCBWH", "FXCZBLG", "FRYDDZ", "HZSMTFX3", "ESEDDZ", "FRFBCTA", "FXB2B", "TJLAFX", "JPPXTJ", "SMTCN",
				"FRFBCJA", "FRFBCBE", "FXCZBLG2", "FXMX", "FRFBCNI", "FRFBCNE", "FRFBCFX", "XNPTXC", "NGJUMIAJU", "FRFBCCW",
				"FRFBCSE", "HKZYLS", "FRFBCUP", "NGJUMIAFC", "AU4PXHXY2", "INPAYTM", "CDFBCJC", "HZSMTFX6", "SUMAITONG",
				"KEJUMIAFC", "FRFBCBO", "FRFBCBA", "AU4PXHXY", "KEJUMIAJC", "FRFBCHY", "HZSMTFX5", "CDFBCC", "NGJUMIAJC",
				"HZSMTFX", "FAFBACD", "CNLAZADB", "FAFBACH", "CNLAZADA", "CDFBCA", "TRTUERQI", "USFBSEA", "CDFBCB",
				"JPZYCK", "NGJUMIA", "FRFBACDI", "NGJUMIA1", "ITHYC", "B2BREXIAOWH", "FRFBCCESTA", "CODTJDB", "ICJUMIA",
				"GB4PXLUTJ2", "DZTJHN", "DEFNTJ", "GB4PXLUTJ1", "DETUICANG", "YBSATJ2", "USFBAWHL", "FXHKGC", "FRFBCOMS",
				"CAHZCLM", "FRFBCFR", "NGJUMIAA", "FRFBCAA", "USZYCB", "NGFBCAA", "AEFBNSS", "SAFBNNNN", "AEHZCYB",
				"SAFBNNN", "FRFBCZA", "AEFTBCC", "AEFBNNN", "AEFBSSS", "TCFBCAA", "SAFAYY", "AEHZCYBB", "AEFTBCCCCCCC",
				"AEFTBC", "AEFTBCCC", "SAFAY", "FXFXC", "AEFTBCCCCC", "SAFAYYY", "AEFBNGCC", "AEHZCYBBB", "AEFXNOON05",
				"AEHZCYBBBB", "AEFBSSQQ", "AEFBSZLL", "AEFBNGC", "AEFBSZLLL", "AEFBSSQ", "SAFAYYYY", "AEFBSWYS", "AEFBSGC",
				"AEHZCYB05", "AEFBSSQE", "SAFBNGC", "AEFBSSLL", "MXFBM03", "RUFENXIAO", "MXFBM04", "MXFBM01", "MXFBWPL",
				"MXFBM02", "MXFBM08", "MXFBM05", "MXFBM09", "MXFBM06", "MXFBM20190528", "MXFBM07", "YYC", "AEFBSWD", "TM",
				"XCWH" };
		String[] str1 = new String[] { "HZSMTFX2", "SZWZTS", "GBBR", "FXJFKGC", "UKTJWH", "GBRU", "EUK", "WZUSPX", "DEPXTJ",
				"HKB2BC", "USLAWH", "KEMNGC", "DEEDXN", "GBZTYKD", "ESTJWH", "USLAW", "AUPXTJ", "SZTSWH", "FXLAXGC",
				"UKCBWH", "MXWH", "CZ4PXDZ", "GBYKDFX", "FREDCGC", "SZLIUJIUC", "XNBLC", "HZSMTFX4", "HKTJWH", "FXLAWH",
				"GBSPAW", "FXDHQD", "FXRUWJ", "UK", "UKLT", "GBNY", "FRFBCCD", "USCBWH", "FXCZBLG", "GBYKDDZ", "FRYDDZ",
				"HZSMTFX3", "ESEDDZ", "FRFBCTA", "GBYKDFX2", "FXB2B", "TJLAFX", "JPPXTJ", "YBTB", "CAPXTJ", "SMTCN",
				"YBMYXNC", "FRFBCJA", "CZ4PXFX", "FRFBCBE", "FXCZBLG2", "FXMX", "FXLAWH2", "FRFBCNI", "FRFBCNE",
				"ELSSMTDFC", "FRFBCFX", "XNPTXC", "NGJUMIAJU", "FRFBCCW", "FRFBCSE", "HKZYLS", "FRFBCUP", "NGJUMIAFC",
				"AU4PXHXY2", "INPAYTM", "CDFBCJC", "HZSMTFX6", "SUMAITONG", "KEJUMIAFC", "CNSMTDFC", "FRFBCBO", "FRFBCBA",
				"AU4PXHXY", "KEJUMIAJC", "FRFBCHY", "HZSMTFX5", "CDFBCC", "NGJUMIAJC", "HZSMTFX", "FAFBACD", "YBSATJ",
				"CNLAZADB", "FAFBACH", "CNLAZADA", "CDFBCA", "TRTUERQI", "USFBSEA", "CNGYSTO", "CDFBCB", "JPZYCK",
				"NGJUMIA", "SUMAITAE", "DS", "FRFBACDI", "NGJUMIA1", "ITHYC", "B2BREXIAOWH", "DEHAIER", "ESHAIER", "MXTJWH",
				"PLHYTJC", "FRFBCCESTA", "DBARAMEXTJ", "ITHAIER", "CODTJDB", "ICJUMIA", "YKDKHTJ", "GB4PXLUTJ2", "DZTJHN",
				"FXDJWH", "GBFNTJ2", "DEFNTJ", "GB4PXLUTJ1", "SACYTJ", "DETUICANG", "GBFNTJ", "DEHZC", "GBBMHTJ2",
				"YBSATJ2", "ESTJWHFX", "USLATJC", "ESTJWHFZ", "INHZCCC", "ESTJWHDSF", "USZYCE", "AEFTBCCCC", "HKTJCK",
				"DETUICANGG", "ESTJWH2", "ESHYTJC", "USFBAWHL", "FXHKGC", "DEHEYUEC", "HKHZCCWC", "DEHEYTJ", "WULIULS",
				"FRFBCOMS", "CAHZCLM", "FRFBCFR", "ESFBAWHE", "NGJUMIAA", "FRFBCAA", "USZYCB", "NGFBCAA", "AEFBNSS",
				"SAFBNNNN", "AEHZCYB", "CNHYCSDD", "SAFBNNN", "FRFBCZA", "AEFTBCC", "AEFBNNN", "AEFBSSS", "TCFBCAA",
				"SAFAYY", "AEFBSSVT", "AEFBSAB", "AEFBSMLY", "AEHZCYBB", "AEFTBCCCCCCC", "AEFTBC", "AEHZCCC", "AEFTBCCC",
				"AEFBSAA", "SAFAY", "FXFXC", "AEFBSYOKE", "AENOON", "AEFTBCCCCC", "SAFAYYY", "AEFBNGCC", "AEHZCYBBB",
				"AEFXNOON05", "AEHZCYBBBB", "AEFBSSQQ", "AEFXNOON04", "AEFXNOON03", "AEFBSZLL", "AEFBNGC", "AEFBSZLLL",
				"AEFXNOON02", "AEFBSSQ", "SAFAYYYY", "AEFXNOON01", "AEFBSWYS", "AEFBNNO", "AEFBSGC", "AEHZCYB05",
				"AEFBSSQE", "SAFBNGC", "AEFBSSLL", "MXFBM03", "RUFENXIAO", "MXFBM04", "MXFBM01", "MXFBWPL", "MXFBM02",
				"MXFBM08", "MXFBM05", "MXFBM09", "MXFBM06", "MXFBM20190528", "VIDAXLL", "CPGYSDFC01", "MXFBM07",
				"FXDEGYSDFCDC", "DEFXYJDF01", "YYC", "YUBESZWH", "AEFBSWD", "GZYYC", "SZ", "TM", "GBYKDFZ", "FZDZN",
				"ZYCXGSB", "FZPCWH", "ZYCXGSBB", "XCWH", "B2BXNWH", "PHZYC01", "BANYIWH" };
		
		
	     String[]	str2 = new String [] {"ESFBAWHE","UKFBAWHE","FRFBAWHE","DEFBAWHE","USFBAWHO","USFBAWHS","UKFBAWHD","CAFBAWHS","ITFBAWHK","FRFBAWHK","ESFBAWHK","RUEKT","YBMYXNC","GZYYC","WZDFWH","JPFBYISA","JPFBYINI","FXQHBSWH","CAFBAS","CAFBAW","ESFBR","FRFBB","ITFBW","DEFBK","UKFBW","FRFBW","RUWJ","KMMP","KMKSA","DEMBB","ITFBS","FRFBT","DEPX","UKPX","EBHKZZWH","EBSZZZWH","USFBAWHG","USFBAWHB","JPFBAWHE","JPFBAWHD","JPFBAWHC","JPFBAWHB","ITFBAWHB","FRFBAWHB","ESFBAWHB","DEFBAWHB","CNSZ","EBQHBSWH","EBQHZZWH","QHZZWH","QHBSWH","YUBESZWH","VIDAXI","NEWAIM","VGWH","DZWH","JPFBAWH","DEFBAWH","UKFBAWH","MXWH","PCWH","GBRUW","EUK","UK","NY","SZ","SZXL","ZHJNB","DLPF","LINGCAI","USFBW","RUEBF","JPFBALY","USFBAWHR","JPFBYMD","USFBAWHK","CAFBAWHK","MXFBAWHK","UKFBA","USFBYISINA","UKFBYISINA","ESFBYISINA","FRFBYISINA","UKLT","YBTB","DEFBAWHM","ESFBAWHM","UKFBAWHG","ESFBAWHG","FRFBAWHG","UKFBAWHJ","DEFBAWHI","ESFBAWHI","UKFBAWHK","DEFBAWHK","ST","UKFBAWHH","ESFBAWHH","FRFBAWHH","ITFBAWHH","JPFBAWHG","JPFBAWHF","ESFBAWHL","UKFBAWHO","ESSMTWH","UKFBAWHR","FZDZN","UKFBAZ","FRFBAZ","MXTJWH","UKTJWH","DEFBAW","ITFBASL","ESTJWH","HKTJWH","CAPXTJ","AUPXTJ","FXRUWJ","USFBAXM","GBFBAHHT","FRFBAHHT","ITFBAHHT","XNFHC","MXFBAHLD","FXLAWH2","WULIAOWH","GBFBAMHS","DEFBAMHS","ESFBAMHS","ITFBAMHS","FRFBAMHS","USFBAXCST","DEFNTG","AUFNTG","DGWLC","USFNTG","IDJDYJD","SZXWFN","GBFBAMQ","FXJFKGC","DEFBAXB","SHOUHOUBEIPINWH","DGXWFN","ESWXDZ","SDLDF","USEYKD","IDXNSP","FXDHQD","DZXNQD","PEIJIANWH","GBFBAEL","DEFBAEL","FRFBAEL","ITFBAEL","ESFBAEL","CAFBAXM","GBZTYKD","GBYKDFX","GBYKDDZ","GBYKDFZ","YKDKHTJ","MYXNSP","HKB2BC","KA","DSFHQB","GBFNTJ","GBFNTJ2","DEFBABE","FRFBABE","PEIJIANWX","DZYJDFC","HZSMTFX2","USFBWMX","HZSMTFX4","ITFBAELE","FZPCWH","CZ4PXFX","GB4PXDSF","P_TYDFX","FRFBARD","DBARAMEXTJ","GB4PXLU2","GB4PXLU3","GBYKDDSF2","GBYKDFX2","GBYKDDZ2","DEDFCK","PTDFCK","USDFCK","MYDFCK","GBBMHTJ2","CZ4PXCZPT1","CZ4PXCZPT2","BANYIWH","SACYTJ","AUDFCK","PLDFCK","BEDFCK","YBSATJ","DZCZBLG","DZCZBLG1","DEWHDSF","XDNEWEGG","CNSMTDFC","ELSSMTDFC","SZLIUJIUC","AUSY","USLAA","GBFBAFOR","FBFBAFOR","DEFBAFOR","ITFBAFOR","ESFBAFOR","USFBART","ZYCXGSB","USFBAM","HTDK","ITALYJC","SPAINJC","DERMJC","NGFBJ02","AEFBSSVT","AEFBSMLY","XIAWANXL","RUIMULE","DEHAIER","ITHAIER","ESHAIER","ESTJWH2","AEFBSYOKE","USFBADY","SUMAITAE","USFBAZHE","DSFTS","ESTJWHFZ","ESTJWHDSF","ESTJWHFX","CNFBWHANZ","MXFBAMHS","PHSHOPEE","THSHOPEE","CNGYSTO","WULIULS","AUFBAQJJ","DEHEYTJ","GBFLYING","USFBAOA","GBFBAOA","DEFBAOA","FRFBAOA","ITFBAOA","ESFBAOA","DS","ITGYSDF","EKJUMIASS","USGYSTO","CLEARASIL","DETUICANGG","DEHEYUEC","INFBAYOKE","JPFBANOJ","HTXNC","UKFBAAZON","ITFBAAZON","ESFBAAZON","DEFBAAZON","FRFBAAZON","UKAMAZON","FRAMAZON","DEAMAZON","ESAMAZON","USFBAAVI","DEBONTALE","USFBACDY","CAFBACDY","GBFBACDY","DEFBACDY","FRFBACDY","ITFBACDY","ESFBACDY","JPFBACDY","CAFBAJSS","HKTJCK","HDYGMX","RUYJDA","USLATJC","CNHYCSD","ESHYTJC","PLHYTJC","ESFBAZAAA","USFBAYD","JPFBALA","DEHZC","AEFBSAA","AEFBSAB","CHHZAA","USZYCC","USZYCE","DZTS","AENOON","INHZCCC","FRFBADE","CNHYCSDD","GBDSFLD","AEHZCCC","AEFTBCCCC","HKHZCCWC","GBFBAZJ","VIDAXLL","ZYCXGSBB","AEFBNNO","USFBWJU","USFBWYY","LYSOL","CNHYCSDDD","JPFBAFX","JPFBADSF","NGJUMIAZA","EUFBWEU","JPCHCGC","TMCS","B2BXNWH","FXDJWH","FXXN","DSFXN","DZXN","CAFBATZE","GBFBATZE","DEFBATZE","FRFBATZE","ESFBATZE","JPFBATZE","EUFBWENS","GBFBA06","DEFBA07","FRFBA07","ITFBA07","ESFBA07","SZKP","SDWH04","INFBA02","USFBW01","USFBW02","USFBW03","USFBW04","USFBW05","USFBW06","USFBW07","USFBW08","USFBW09","USFBW10","USFBW11","USFBW12","USFBW13","USFBW14","USFBW15","USFBW16","USFBW17","KPDF","USFBW18","USFBW19","USFBW20","USFBW21","USFBW22","USFBW23","USFBW24","USFBW25","USFBW26","USFBW27","USFBW28","HKZYC15","NGJUMIA01","ICJUMIA01","PHZYC01","CPGYSDFC01","DSFSNT01","DSFFBW01","DSFMAJUMIA02","DZGX","AEFXNOON01","AEFXNOON02","AEFXNOON03","AEFXNOON04","DEFXYJDF01","DDSDSFJPFBA","FHHC","FXDEGYSDFCDC","FXUSGYSDFCDC","FXPLGYSDFCDC","USFXYJDF01","USFXYJDF02","USDSFYJDF01","CAFBAKYYJ190511","CAFBAJSS190511","DEFBAWM190511","ESFBAWM190511","DEFBASZ190511","ESFBASZ190511","GBFBA20190516","DEFBA20190516","FRFBA20190516","ITFBA20190516","ESFBA20190516","JPFBA20190516","DSFNX","ESFBA20190522","INFBA20190525","FRMM20190528","FRMM20190530","CAFBA20190624","NGJUMIA20190627","GBFBA20190627","FRFFBA20190627","DEFBA20190627","ITFBA20190627","MMNC","ICJUMIA20190703","JHZZ","GBFBA20190706","DEFBA20190706","FRFBA20190704","ITFBA20190706","ESFBA20190706","USFBA20190706","CAFBA20190706","USFBA20190710","HK20190711","GBVIDA20190717","DEVIDA20190717","FRVIDA20190717","ITVIDA20190717","ESVIDA20190717","BEVIDA20190717","ITFBA20190722","GBFBA20190722","DEFBA20190722","FRFBA20190722","ESFBA20190722","AEFBN20190722"};

		List<String> list = Arrays.asList(str);
		System.out.println(list.size());
		List<String>  list1 =Arrays.asList(str1);
		System.out.println(list1.size());
		List<String>  list2 =Arrays.asList(str2);
		System.out.println(list2.size());
		
		
		

		  int k=0;
		for( int i = 0;i<list1.size();i++)
		{
             
			if(list2.contains(list1.get(i))==true) {
				 k++;
				System.out.println(k+"-----"+list1.get(i));
				
			};

		}

	}
	
	
}
